// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package firehose

const (

	// Another modification has already happened. Fetch VersionId again and use
	// it to update the destination.
	ErrCodeConcurrentModificationException = "ConcurrentModificationException"

	// The specified input parameter has an value that is not valid.
	ErrCodeInvalidArgumentException = "InvalidArgumentException"

	// You have already reached the limit for a requested resource.
	ErrCodeLimitExceededException = "LimitExceededException"

	// The resource is already in use and not available for this operation.
	ErrCodeResourceInUseException = "ResourceInUseException"

	// The specified resource could not be found.
	ErrCodeResourceNotFoundException = "ResourceNotFoundException"

	// The service is unavailable, back off and retry the operation. If you continue
	// to see the exception, throughput limits for the delivery stream may have
	// been exceeded. For more information about limits and how to request an increase,
	// see Amazon Kinesis Firehose Limits (http://docs.aws.amazon.com/firehose/latest/dev/limits.html).
	ErrCodeServiceUnavailableException = "ServiceUnavailableException"
)
