// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package marketplacedeployment provides the client and types for making API
// requests to AWS Marketplace Deployment Service.
//
// The AWS Marketplace Deployment Service supports the Quick Launch experience,
// which is a deployment option for software as a service (SaaS) products. Quick
// Launch simplifies and reduces the time, resources, and steps required to
// configure, deploy, and launch a products. The AWS Marketplace Deployment
// Service provides sellers with a secure method for passing deployment parameters
// (for example, API keys and external IDs) to buyers during the Quick Launch
// experience.
//
// See https://docs.aws.amazon.com/goto/WebAPI/marketplace-deployment-2023-01-25 for more information on this service.
//
// See marketplacedeployment package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/marketplacedeployment/
//
// # Using the Client
//
// To contact AWS Marketplace Deployment Service with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the AWS Marketplace Deployment Service client MarketplaceDeployment for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/marketplacedeployment/#New
package marketplacedeployment
