package api

var legacyStructNames = map[string]string{
	"ACM":                             "ACM",
	"ACM PCA":                         "ACM-PCA",
	"API Gateway":                     "Amazon API Gateway",
	"AccessAnalyzer":                  "Access Analyzer",
	"Account":                         "AWS Account",
	"Alexa For Business":              "Alexa For Business",
	"Amplify":                         "Amplify",
	"AmplifyBackend":                  "AmplifyBackend",
	"AmplifyUIBuilder":                "AWS Amplify UI Builder",
	"ApiGatewayManagementApi":         "AmazonApiGatewayManagementApi",
	"ApiGatewayV2":                    "AmazonApiGatewayV2",
	"App Mesh":                        "AWS App Mesh",
	"AppConfig":                       "AppConfig",
	"AppConfigData":                   "AWS AppConfig Data",
	"AppIntegrations":                 "Amazon AppIntegrations Service",
	"AppRunner":                       "AWS App Runner",
	"AppStream":                       "Amazon AppStream",
	"AppSync":                         "AWSAppSync",
	"Appflow":                         "Amazon Appflow",
	"Application Auto Scaling":        "Application Auto Scaling",
	"Application Discovery Service":   "AWS Application Discovery Service",
	"Application Insights":            "Application Insights",
	"ApplicationCostProfiler":         "AWS Application Cost Profiler",
	"Athena":                          "Amazon Athena",
	"AuditManager":                    "AWS Audit Manager",
	"Auto Scaling":                    "Auto Scaling",
	"Auto Scaling Plans":              "AWS Auto Scaling Plans",
	"Backup":                          "AWS Backup",
	"Backup Gateway":                  "AWS Backup Gateway",
	"Batch":                           "AWS Batch",
	"Braket":                          "Braket",
	"Budgets":                         "AWSBudgets",
	"Chime":                           "Amazon Chime",
	"Chime SDK Identity":              "Amazon Chime SDK Identity",
	"Chime SDK Media Pipelines":       "Amazon Chime SDK Media Pipelines",
	"Chime SDK Meetings":              "Amazon Chime SDK Meetings",
	"Chime SDK Messaging":             "Amazon Chime SDK Messaging",
	"Cloud9":                          "AWS Cloud9",
	"CloudControl":                    "CloudControlApi",
	"CloudDirectory":                  "Amazon CloudDirectory",
	"CloudFormation":                  "AWS CloudFormation",
	"CloudFront":                      "CloudFront",
	"CloudHSM":                        "CloudHSM",
	"CloudHSM V2":                     "CloudHSM V2",
	"CloudSearch":                     "Amazon CloudSearch",
	"CloudSearch Domain":              "Amazon CloudSearch Domain",
	"CloudTrail":                      "CloudTrail",
	"CloudWatch":                      "CloudWatch",
	"CloudWatch Events":               "Amazon CloudWatch Events",
	"CloudWatch Logs":                 "Amazon CloudWatch Logs",
	"CodeBuild":                       "AWS CodeBuild",
	"CodeCommit":                      "CodeCommit",
	"CodeDeploy":                      "CodeDeploy",
	"CodeGuru Reviewer":               "CodeGuruReviewer",
	"CodeGuruProfiler":                "Amazon CodeGuru Profiler",
	"CodePipeline":                    "CodePipeline",
	"CodeStar":                        "CodeStar",
	"CodeStar connections":            "AWS CodeStar connections",
	"Cognito Identity":                "Amazon Cognito Identity",
	"Cognito Identity Provider":       "Amazon Cognito Identity Provider",
	"Cognito Sync":                    "Amazon Cognito Sync",
	"Comprehend":                      "Amazon Comprehend",
	"ComprehendMedical":               "ComprehendMedical",
	"Compute Optimizer":               "AWS Compute Optimizer",
	"Config Service":                  "Config Service",
	"Connect":                         "Amazon Connect",
	"Connect Contact Lens":            "Amazon Connect Contact Lens",
	"ConnectParticipant":              "Amazon Connect Participant",
	"Cost Explorer":                   "AWS Cost Explorer",
	"Cost and Usage Report Service":   "AWS Cost and Usage Report Service",
	"Customer Profiles":               "Customer Profiles",
	"DAX":                             "Amazon DAX",
	"DLM":                             "Amazon DLM",
	"Data Pipeline":                   "AWS Data Pipeline",
	"DataBrew":                        "AWS Glue DataBrew",
	"DataExchange":                    "AWS Data Exchange",
	"DataSync":                        "DataSync",
	"Database Migration Service":      "AWS Database Migration Service",
	"Detective":                       "Amazon Detective",
	"DevOps Guru":                     "Amazon DevOps Guru",
	"Device Farm":                     "AWS Device Farm",
	"Direct Connect":                  "AWS Direct Connect",
	"Directory Service":               "Directory Service",
	"DocDB":                           "Amazon DocDB",
	"DynamoDB":                        "DynamoDB",
	"DynamoDB Streams":                "Amazon DynamoDB Streams",
	"EBS":                             "Amazon EBS",
	"EC2":                             "Amazon EC2",
	"EC2 Instance Connect":            "EC2 Instance Connect",
	"ECR":                             "Amazon ECR",
	"ECR PUBLIC":                      "Amazon ECR Public",
	"ECS":                             "Amazon ECS",
	"EFS":                             "EFS",
	"EKS":                             "Amazon EKS",
	"EMR":                             "Amazon EMR",
	"EMR Serverless":                  "EMR Serverless",
	"EMR containers":                  "Amazon EMR Containers",
	"ElastiCache":                     "Amazon ElastiCache",
	"Elastic Beanstalk":               "Elastic Beanstalk",
	"Elastic Inference":               "Amazon Elastic Inference",
	"Elastic Load Balancing":          "Elastic Load Balancing",
	"Elastic Load Balancing v2":       "Elastic Load Balancing v2",
	"Elastic Transcoder":              "Amazon Elastic Transcoder",
	"Elasticsearch Service":           "Amazon Elasticsearch Service",
	"EventBridge":                     "Amazon EventBridge",
	"Evidently":                       "Amazon CloudWatch Evidently",
	"FMS":                             "FMS",
	"FSx":                             "Amazon FSx",
	"Firehose":                        "Firehose",
	"FraudDetector":                   "Amazon Fraud Detector",
	"GameLift":                        "Amazon GameLift",
	"GameSparks":                      "GameSparks",
	"Glacier":                         "Amazon Glacier",
	"Global Accelerator":              "AWS Global Accelerator",
	"Glue":                            "AWS Glue",
	"Greengrass":                      "AWS Greengrass",
	"GreengrassV2":                    "AWS GreengrassV2",
	"GroundStation":                   "AWS Ground Station",
	"GuardDuty":                       "Amazon GuardDuty",
	"Health":                          "AWSHealth",
	"HealthLake":                      "HealthLake",
	"Honeycode":                       "Honeycode",
	"IAM":                             "IAM",
	"Import Export":                   "AWS Import/Export",
	"Inspector":                       "Amazon Inspector",
	"Inspector2":                      "Inspector2",
	"IoT":                             "AWS IoT",
	"IoT 1Click Devices Service":      "AWS IoT 1-Click Devices Service",
	"IoT 1Click Projects":             "AWS IoT 1-Click Projects",
	"IoT Data Plane":                  "AWS IoT Data Plane",
	"IoT Events":                      "AWS IoT Events",
	"IoT Events Data":                 "AWS IoT Events Data",
	"IoT Jobs Data Plane":             "AWS IoT Jobs Data Plane",
	"IoT Wireless":                    "AWS IoT Wireless",
	"IoTAnalytics":                    "AWS IoT Analytics",
	"IoTFleetHub":                     "AWS IoT Fleet Hub",
	"IoTSecureTunneling":              "AWS IoT Secure Tunneling",
	"IoTSiteWise":                     "AWS IoT SiteWise",
	"IoTThingsGraph":                  "AWS IoT Things Graph",
	"IoTTwinMaker":                    "AWS IoT TwinMaker",
	"IotDeviceAdvisor":                "AWSIoTDeviceAdvisor",
	"KMS":                             "KMS",
	"Kafka":                           "Kafka",
	"KafkaConnect":                    "Kafka Connect",
	"Keyspaces":                       "Amazon Keyspaces",
	"Kinesis":                         "Kinesis",
	"Kinesis Analytics":               "Kinesis Analytics",
	"Kinesis Analytics V2":            "Kinesis Analytics V2",
	"Kinesis Video":                   "Kinesis Video",
	"Kinesis Video Archived Media":    "Kinesis Video Archived Media",
	"Kinesis Video Media":             "Kinesis Video Media",
	"Kinesis Video Signaling":         "Amazon Kinesis Video Signaling Channels",
	"LakeFormation":                   "AWS Lake Formation",
	"Lambda":                          "AWS Lambda",
	"Lex Model Building Service":      "Amazon Lex Model Building Service",
	"Lex Models V2":                   "Lex Models V2",
	"Lex Runtime Service":             "Amazon Lex Runtime Service",
	"Lex Runtime V2":                  "Lex Runtime V2",
	"License Manager":                 "AWS License Manager",
	"Lightsail":                       "Amazon Lightsail",
	"Location":                        "Amazon Location Service",
	"LookoutEquipment":                "LookoutEquipment",
	"LookoutMetrics":                  "LookoutMetrics",
	"LookoutVision":                   "Amazon Lookout for Vision",
	"MTurk":                           "Amazon MTurk",
	"MWAA":                            "AmazonMWAA",
	"Machine Learning":                "Amazon Machine Learning",
	"Macie":                           "Amazon Macie",
	"Macie2":                          "Amazon Macie 2",
	"ManagedBlockchain":               "ManagedBlockchain",
	"Marketplace Catalog":             "AWS Marketplace Catalog",
	"Marketplace Commerce Analytics":  "AWS Marketplace Commerce Analytics",
	"Marketplace Entitlement Service": "AWS Marketplace Entitlement Service",
	"Marketplace Metering":            "AWSMarketplace Metering",
	"MediaConnect":                    "AWS MediaConnect",
	"MediaConvert":                    "MediaConvert",
	"MediaLive":                       "MediaLive",
	"MediaPackage":                    "MediaPackage",
	"MediaPackage Vod":                "MediaPackage Vod",
	"MediaStore":                      "MediaStore",
	"MediaStore Data":                 "MediaStore Data",
	"MediaTailor":                     "MediaTailor",
	"MemoryDB":                        "Amazon MemoryDB",
	"Migration Hub":                   "AWS Migration Hub",
	"Migration Hub Refactor Spaces":   "AWS Migration Hub Refactor Spaces",
	"MigrationHub Config":             "AWS Migration Hub Config",
	"MigrationHubStrategy":            "Migration Hub Strategy Recommendations",
	"Mobile":                          "AWS Mobile",
	"Mobile Analytics":                "Amazon Mobile Analytics",
	"Neptune":                         "Amazon Neptune",
	"Network Firewall":                "Network Firewall",
	"NetworkManager":                  "NetworkManager",
	"OpenSearch":                      "Amazon OpenSearch Service",
	"OpsWorks":                        "AWS OpsWorks",
	"OpsWorksCM":                      "OpsWorksCM",
	"Organizations":                   "Organizations",
	"Outposts":                        "Outposts",
	"PI":                              "AWS PI",
	"Panorama":                        "Panorama",
	"Personalize":                     "Amazon Personalize",
	"Personalize Events":              "Amazon Personalize Events",
	"Personalize Runtime":             "Amazon Personalize Runtime",
	"Pinpoint":                        "Amazon Pinpoint",
	"Pinpoint Email":                  "Pinpoint Email",
	"Pinpoint SMS Voice":              "Pinpoint SMS Voice",
	"Pinpoint SMS Voice V2":           "Amazon Pinpoint SMS Voice V2",
	"Polly":                           "Amazon Polly",
	"Pricing":                         "AWS Pricing",
	"Proton":                          "AWS Proton",
	"QLDB":                            "QLDB",
	"QLDB Session":                    "QLDB Session",
	"QuickSight":                      "Amazon QuickSight",
	"RAM":                             "RAM",
	"RDS":                             "Amazon RDS",
	"RDS Data":                        "AWS RDS DataService",
	"RUM":                             "CloudWatch RUM",
	"Redshift":                        "Amazon Redshift",
	"Redshift Data":                   "Redshift Data API Service",
	"Rekognition":                     "Amazon Rekognition",
	"Resource Groups":                 "Resource Groups",
	"Resource Groups Tagging API":     "AWS Resource Groups Tagging API",
	"RoboMaker":                       "RoboMaker",
	"Route 53":                        "Route 53",
	"Route 53 Domains":                "Amazon Route 53 Domains",
	"Route53 Recovery Cluster":        "Route53 Recovery Cluster",
	"Route53 Recovery Control Config": "AWS Route53 Recovery Control Config",
	"Route53 Recovery Readiness":      "AWS Route53 Recovery Readiness",
	"Route53Resolver":                 "Route53Resolver",
	"S3":                              "Amazon S3",
	"S3 Control":                      "AWS S3 Control",
	"S3Outposts":                      "Amazon S3 Outposts",
	"SES":                             "Amazon SES",
	"SESv2":                           "Amazon SES V2",
	"SFN":                             "AWS SFN",
	"SMS":                             "SMS",
	"SNS":                             "Amazon SNS",
	"SQS":                             "Amazon SQS",
	"SSM":                             "Amazon SSM",
	"SSM Contacts":                    "SSM Contacts",
	"SSM Incidents":                   "SSM Incidents",
	"SSO":                             "SSO",
	"SSO Admin":                       "SSO Admin",
	"SSO OIDC":                        "SSO OIDC",
	"STS":                             "AWS STS",
	"SWF":                             "Amazon SWF",
	"SageMaker":                       "SageMaker",
	"SageMaker A2I Runtime":           "Amazon Augmented AI Runtime",
	"SageMaker FeatureStore Runtime":  "Amazon SageMaker Feature Store Runtime",
	"SageMaker Runtime":               "Amazon SageMaker Runtime",
	"Sagemaker Edge":                  "Amazon Sagemaker Edge Manager",
	"Secrets Manager":                 "AWS Secrets Manager",
	"SecurityHub":                     "AWS SecurityHub",
	"ServerlessApplicationRepository": "AWSServerlessApplicationRepository",
	"Service Catalog":                 "AWS Service Catalog",
	"Service Catalog AppRegistry":     "AppRegistry",
	"Service Quotas":                  "Service Quotas",
	"ServiceDiscovery":                "ServiceDiscovery",
	"Shield":                          "AWS Shield",
	"SimpleDB":                        "Amazon SimpleDB",
	"Snow Device Management":          "AWS Snow Device Management",
	"Snowball":                        "Amazon Snowball",
	"Storage Gateway":                 "AWS Storage Gateway",
	"Support":                         "AWS Support",
	"Textract":                        "Amazon Textract",
	"Timestream Query":                "Timestream Query",
	"Timestream Write":                "Timestream Write",
	"Transcribe":                      "Amazon Transcribe Service",
	"Transcribe Streaming":            "Amazon Transcribe Streaming Service",
	"Transfer":                        "AWS Transfer",
	"Translate":                       "Amazon Translate",
	"Voice ID":                        "Amazon Voice ID",
	"WAF":                             "WAF",
	"WAF Regional":                    "WAF Regional",
	"WAFV2":                           "WAFV2",
	"WellArchitected":                 "Well-Architected",
	"Wisdom":                          "Amazon Connect Wisdom Service",
	"WorkDocs":                        "Amazon WorkDocs",
	"WorkLink":                        "WorkLink",
	"WorkMail":                        "Amazon WorkMail",
	"WorkMailMessageFlow":             "Amazon WorkMail Message Flow",
	"WorkSpaces":                      "Amazon WorkSpaces",
	"WorkSpaces Web":                  "Amazon WorkSpaces Web",
	"XRay":                            "AWS X-Ray",
	"amp":                             "Amazon Prometheus Service",
	"billingconductor":                "AWSBillingConductor",
	"codeartifact":                    "CodeArtifact",
	"codestar notifications":          "AWS CodeStar Notifications",
	"drs":                             "drs",
	"finspace":                        "finspace",
	"finspace data":                   "FinSpace Data",
	"fis":                             "FIS",
	"forecast":                        "Amazon Forecast Service",
	"forecastquery":                   "Amazon Forecast Query Service",
	"grafana":                         "Amazon Managed Grafana",
	"identitystore":                   "IdentityStore",
	"imagebuilder":                    "imagebuilder",
	"ivs":                             "Amazon IVS",
	"ivschat":                         "ivschat",
	"kendra":                          "kendra",
	"mgn":                             "mgn",
	"mq":                              "AmazonMQ",
	"nimble":                          "AmazonNimbleStudio",
	"rbin":                            "Amazon Recycle Bin",
	"resiliencehub":                   "AWS Resilience Hub",
	"savingsplans":                    "AWSSavingsPlans",
	"schemas":                         "Schemas",
	"signer":                          "signer",
	"synthetics":                      "Synthetics",
}
