language: go

sudo: required

os:
    - linux
    - osx
    - windows

go:
    - 1.6.x
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - tip

matrix:
    allow_failures:
        - go: tip
    include:
        - os: linux
          go: 1.5.x
          # Use Go 1.5's vendoring experiment for 1.5 tests.
          env: GO15VENDOREXPERIMENT=1
        - os: osx
          go: 1.5.x
          # Use Go 1.5's vendoring experiment for 1.5 tests.
          env: GO15VENDOREXPERIMENT=1
        - os: windows
          go: 1.5.x
          # Use Go 1.5's vendoring experiment for 1.5 tests.
          env: GO15VENDOREXPERIMENT=1

script:
  - if [ $TRAVIS_GO_VERSION == "tip" ] ||
    [ $TRAVIS_GO_VERSION == "1.11.x" ] || 
    [ $TRAVIS_GO_VERSION == "1.10.x" ]; then
    make ci-test;
    else
    make unit-old-go-race-cover;
    fi

branches:
  only:
    - master
