package ssm

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

import (
	"time"

	"github.com/awslabs/aws-sdk-go/aws"
)

// CreateAssociationRequest generates a request for the CreateAssociation operation.
func (c *SSM) CreateAssociationRequest(input *CreateAssociationInput) (req *aws.Request, output *CreateAssociationOutput) {
	if opCreateAssociation == nil {
		opCreateAssociation = &aws.Operation{
			Name:       "CreateAssociation",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opCreateAssociation, input, output)
	output = &CreateAssociationOutput{}
	req.Data = output
	return
}

func (c *SSM) CreateAssociation(input *CreateAssociationInput) (output *CreateAssociationOutput, err error) {
	req, out := c.CreateAssociationRequest(input)
	output = out
	err = req.Send()
	return
}

var opCreateAssociation *aws.Operation

// CreateAssociationBatchRequest generates a request for the CreateAssociationBatch operation.
func (c *SSM) CreateAssociationBatchRequest(input *CreateAssociationBatchInput) (req *aws.Request, output *CreateAssociationBatchOutput) {
	if opCreateAssociationBatch == nil {
		opCreateAssociationBatch = &aws.Operation{
			Name:       "CreateAssociationBatch",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opCreateAssociationBatch, input, output)
	output = &CreateAssociationBatchOutput{}
	req.Data = output
	return
}

func (c *SSM) CreateAssociationBatch(input *CreateAssociationBatchInput) (output *CreateAssociationBatchOutput, err error) {
	req, out := c.CreateAssociationBatchRequest(input)
	output = out
	err = req.Send()
	return
}

var opCreateAssociationBatch *aws.Operation

// CreateDocumentRequest generates a request for the CreateDocument operation.
func (c *SSM) CreateDocumentRequest(input *CreateDocumentInput) (req *aws.Request, output *CreateDocumentOutput) {
	if opCreateDocument == nil {
		opCreateDocument = &aws.Operation{
			Name:       "CreateDocument",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opCreateDocument, input, output)
	output = &CreateDocumentOutput{}
	req.Data = output
	return
}

func (c *SSM) CreateDocument(input *CreateDocumentInput) (output *CreateDocumentOutput, err error) {
	req, out := c.CreateDocumentRequest(input)
	output = out
	err = req.Send()
	return
}

var opCreateDocument *aws.Operation

// DeleteAssociationRequest generates a request for the DeleteAssociation operation.
func (c *SSM) DeleteAssociationRequest(input *DeleteAssociationInput) (req *aws.Request, output *DeleteAssociationOutput) {
	if opDeleteAssociation == nil {
		opDeleteAssociation = &aws.Operation{
			Name:       "DeleteAssociation",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opDeleteAssociation, input, output)
	output = &DeleteAssociationOutput{}
	req.Data = output
	return
}

func (c *SSM) DeleteAssociation(input *DeleteAssociationInput) (output *DeleteAssociationOutput, err error) {
	req, out := c.DeleteAssociationRequest(input)
	output = out
	err = req.Send()
	return
}

var opDeleteAssociation *aws.Operation

// DeleteDocumentRequest generates a request for the DeleteDocument operation.
func (c *SSM) DeleteDocumentRequest(input *DeleteDocumentInput) (req *aws.Request, output *DeleteDocumentOutput) {
	if opDeleteDocument == nil {
		opDeleteDocument = &aws.Operation{
			Name:       "DeleteDocument",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opDeleteDocument, input, output)
	output = &DeleteDocumentOutput{}
	req.Data = output
	return
}

func (c *SSM) DeleteDocument(input *DeleteDocumentInput) (output *DeleteDocumentOutput, err error) {
	req, out := c.DeleteDocumentRequest(input)
	output = out
	err = req.Send()
	return
}

var opDeleteDocument *aws.Operation

// DescribeAssociationRequest generates a request for the DescribeAssociation operation.
func (c *SSM) DescribeAssociationRequest(input *DescribeAssociationInput) (req *aws.Request, output *DescribeAssociationOutput) {
	if opDescribeAssociation == nil {
		opDescribeAssociation = &aws.Operation{
			Name:       "DescribeAssociation",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opDescribeAssociation, input, output)
	output = &DescribeAssociationOutput{}
	req.Data = output
	return
}

func (c *SSM) DescribeAssociation(input *DescribeAssociationInput) (output *DescribeAssociationOutput, err error) {
	req, out := c.DescribeAssociationRequest(input)
	output = out
	err = req.Send()
	return
}

var opDescribeAssociation *aws.Operation

// DescribeDocumentRequest generates a request for the DescribeDocument operation.
func (c *SSM) DescribeDocumentRequest(input *DescribeDocumentInput) (req *aws.Request, output *DescribeDocumentOutput) {
	if opDescribeDocument == nil {
		opDescribeDocument = &aws.Operation{
			Name:       "DescribeDocument",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opDescribeDocument, input, output)
	output = &DescribeDocumentOutput{}
	req.Data = output
	return
}

func (c *SSM) DescribeDocument(input *DescribeDocumentInput) (output *DescribeDocumentOutput, err error) {
	req, out := c.DescribeDocumentRequest(input)
	output = out
	err = req.Send()
	return
}

var opDescribeDocument *aws.Operation

// GetDocumentRequest generates a request for the GetDocument operation.
func (c *SSM) GetDocumentRequest(input *GetDocumentInput) (req *aws.Request, output *GetDocumentOutput) {
	if opGetDocument == nil {
		opGetDocument = &aws.Operation{
			Name:       "GetDocument",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opGetDocument, input, output)
	output = &GetDocumentOutput{}
	req.Data = output
	return
}

func (c *SSM) GetDocument(input *GetDocumentInput) (output *GetDocumentOutput, err error) {
	req, out := c.GetDocumentRequest(input)
	output = out
	err = req.Send()
	return
}

var opGetDocument *aws.Operation

// ListAssociationsRequest generates a request for the ListAssociations operation.
func (c *SSM) ListAssociationsRequest(input *ListAssociationsInput) (req *aws.Request, output *ListAssociationsOutput) {
	if opListAssociations == nil {
		opListAssociations = &aws.Operation{
			Name:       "ListAssociations",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opListAssociations, input, output)
	output = &ListAssociationsOutput{}
	req.Data = output
	return
}

func (c *SSM) ListAssociations(input *ListAssociationsInput) (output *ListAssociationsOutput, err error) {
	req, out := c.ListAssociationsRequest(input)
	output = out
	err = req.Send()
	return
}

var opListAssociations *aws.Operation

// ListDocumentsRequest generates a request for the ListDocuments operation.
func (c *SSM) ListDocumentsRequest(input *ListDocumentsInput) (req *aws.Request, output *ListDocumentsOutput) {
	if opListDocuments == nil {
		opListDocuments = &aws.Operation{
			Name:       "ListDocuments",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opListDocuments, input, output)
	output = &ListDocumentsOutput{}
	req.Data = output
	return
}

func (c *SSM) ListDocuments(input *ListDocumentsInput) (output *ListDocumentsOutput, err error) {
	req, out := c.ListDocumentsRequest(input)
	output = out
	err = req.Send()
	return
}

var opListDocuments *aws.Operation

// UpdateAssociationStatusRequest generates a request for the UpdateAssociationStatus operation.
func (c *SSM) UpdateAssociationStatusRequest(input *UpdateAssociationStatusInput) (req *aws.Request, output *UpdateAssociationStatusOutput) {
	if opUpdateAssociationStatus == nil {
		opUpdateAssociationStatus = &aws.Operation{
			Name:       "UpdateAssociationStatus",
			HTTPMethod: "POST",
			HTTPPath:   "/",
		}
	}

	req = aws.NewRequest(c.Service, opUpdateAssociationStatus, input, output)
	output = &UpdateAssociationStatusOutput{}
	req.Data = output
	return
}

func (c *SSM) UpdateAssociationStatus(input *UpdateAssociationStatusInput) (output *UpdateAssociationStatusOutput, err error) {
	req, out := c.UpdateAssociationStatusRequest(input)
	output = out
	err = req.Send()
	return
}

var opUpdateAssociationStatus *aws.Operation

type Association struct {
	InstanceID *string `locationName:"InstanceId" type:"string"`
	Name       *string `type:"string"`

	metadataAssociation `json:"-", xml:"-"`
}

type metadataAssociation struct {
	SDKShapeTraits bool `type:"structure"`
}

type AssociationDescription struct {
	Date       *time.Time         `type:"timestamp" timestampFormat:"unix"`
	InstanceID *string            `locationName:"InstanceId" type:"string"`
	Name       *string            `type:"string"`
	Status     *AssociationStatus `type:"structure"`

	metadataAssociationDescription `json:"-", xml:"-"`
}

type metadataAssociationDescription struct {
	SDKShapeTraits bool `type:"structure"`
}

type AssociationFilter struct {
	Key   *string `locationName:"key" type:"string" required:"true"`
	Value *string `locationName:"value" type:"string" required:"true"`

	metadataAssociationFilter `json:"-", xml:"-"`
}

type metadataAssociationFilter struct {
	SDKShapeTraits bool `type:"structure"`
}

type AssociationStatus struct {
	AdditionalInfo *string    `type:"string"`
	Date           *time.Time `type:"timestamp" timestampFormat:"unix" required:"true"`
	Message        *string    `type:"string" required:"true"`
	Name           *string    `type:"string" required:"true"`

	metadataAssociationStatus `json:"-", xml:"-"`
}

type metadataAssociationStatus struct {
	SDKShapeTraits bool `type:"structure"`
}

type CreateAssociationBatchInput struct {
	Entries []*CreateAssociationBatchRequestEntry `locationNameList:"entries" type:"list" required:"true"`

	metadataCreateAssociationBatchInput `json:"-", xml:"-"`
}

type metadataCreateAssociationBatchInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type CreateAssociationBatchOutput struct {
	Failed     []*FailedCreateAssociation `locationNameList:"FailedCreateAssociationEntry" type:"list"`
	Successful []*AssociationDescription  `locationNameList:"AssociationDescription" type:"list"`

	metadataCreateAssociationBatchOutput `json:"-", xml:"-"`
}

type metadataCreateAssociationBatchOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type CreateAssociationBatchRequestEntry struct {
	InstanceID *string `locationName:"InstanceId" type:"string"`
	Name       *string `type:"string"`

	metadataCreateAssociationBatchRequestEntry `json:"-", xml:"-"`
}

type metadataCreateAssociationBatchRequestEntry struct {
	SDKShapeTraits bool `type:"structure"`
}

type CreateAssociationInput struct {
	InstanceID *string `locationName:"InstanceId" type:"string" required:"true"`
	Name       *string `type:"string" required:"true"`

	metadataCreateAssociationInput `json:"-", xml:"-"`
}

type metadataCreateAssociationInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type CreateAssociationOutput struct {
	AssociationDescription *AssociationDescription `type:"structure"`

	metadataCreateAssociationOutput `json:"-", xml:"-"`
}

type metadataCreateAssociationOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type CreateDocumentInput struct {
	Content *string `type:"string" required:"true"`
	Name    *string `type:"string" required:"true"`

	metadataCreateDocumentInput `json:"-", xml:"-"`
}

type metadataCreateDocumentInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type CreateDocumentOutput struct {
	DocumentDescription *DocumentDescription `type:"structure"`

	metadataCreateDocumentOutput `json:"-", xml:"-"`
}

type metadataCreateDocumentOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DeleteAssociationInput struct {
	InstanceID *string `locationName:"InstanceId" type:"string" required:"true"`
	Name       *string `type:"string" required:"true"`

	metadataDeleteAssociationInput `json:"-", xml:"-"`
}

type metadataDeleteAssociationInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DeleteAssociationOutput struct {
	metadataDeleteAssociationOutput `json:"-", xml:"-"`
}

type metadataDeleteAssociationOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DeleteDocumentInput struct {
	Name *string `type:"string" required:"true"`

	metadataDeleteDocumentInput `json:"-", xml:"-"`
}

type metadataDeleteDocumentInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DeleteDocumentOutput struct {
	metadataDeleteDocumentOutput `json:"-", xml:"-"`
}

type metadataDeleteDocumentOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DescribeAssociationInput struct {
	InstanceID *string `locationName:"InstanceId" type:"string" required:"true"`
	Name       *string `type:"string" required:"true"`

	metadataDescribeAssociationInput `json:"-", xml:"-"`
}

type metadataDescribeAssociationInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DescribeAssociationOutput struct {
	AssociationDescription *AssociationDescription `type:"structure"`

	metadataDescribeAssociationOutput `json:"-", xml:"-"`
}

type metadataDescribeAssociationOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DescribeDocumentInput struct {
	Name *string `type:"string" required:"true"`

	metadataDescribeDocumentInput `json:"-", xml:"-"`
}

type metadataDescribeDocumentInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DescribeDocumentOutput struct {
	Document *DocumentDescription `type:"structure"`

	metadataDescribeDocumentOutput `json:"-", xml:"-"`
}

type metadataDescribeDocumentOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type DocumentDescription struct {
	CreatedDate *time.Time `type:"timestamp" timestampFormat:"unix"`
	Name        *string    `type:"string"`
	SHA1        *string    `locationName:"Sha1" type:"string"`
	Status      *string    `type:"string"`

	metadataDocumentDescription `json:"-", xml:"-"`
}

type metadataDocumentDescription struct {
	SDKShapeTraits bool `type:"structure"`
}

type DocumentFilter struct {
	Key   *string `locationName:"key" type:"string" required:"true"`
	Value *string `locationName:"value" type:"string" required:"true"`

	metadataDocumentFilter `json:"-", xml:"-"`
}

type metadataDocumentFilter struct {
	SDKShapeTraits bool `type:"structure"`
}

type DocumentIdentifier struct {
	Name *string `type:"string"`

	metadataDocumentIdentifier `json:"-", xml:"-"`
}

type metadataDocumentIdentifier struct {
	SDKShapeTraits bool `type:"structure"`
}

type FailedCreateAssociation struct {
	Entry   *CreateAssociationBatchRequestEntry `type:"structure"`
	Fault   *string                             `type:"string"`
	Message *string                             `type:"string"`

	metadataFailedCreateAssociation `json:"-", xml:"-"`
}

type metadataFailedCreateAssociation struct {
	SDKShapeTraits bool `type:"structure"`
}

type GetDocumentInput struct {
	Name *string `type:"string" required:"true"`

	metadataGetDocumentInput `json:"-", xml:"-"`
}

type metadataGetDocumentInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type GetDocumentOutput struct {
	Content *string `type:"string"`
	Name    *string `type:"string"`

	metadataGetDocumentOutput `json:"-", xml:"-"`
}

type metadataGetDocumentOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type ListAssociationsInput struct {
	AssociationFilterList []*AssociationFilter `locationNameList:"AssociationFilter" type:"list" required:"true"`
	MaxResults            *int64               `type:"integer"`
	NextToken             *string              `type:"string"`

	metadataListAssociationsInput `json:"-", xml:"-"`
}

type metadataListAssociationsInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type ListAssociationsOutput struct {
	Associations []*Association `locationNameList:"Association" type:"list"`
	NextToken    *string        `type:"string"`

	metadataListAssociationsOutput `json:"-", xml:"-"`
}

type metadataListAssociationsOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type ListDocumentsInput struct {
	DocumentFilterList []*DocumentFilter `locationNameList:"DocumentFilter" type:"list"`
	MaxResults         *int64            `type:"integer"`
	NextToken          *string           `type:"string"`

	metadataListDocumentsInput `json:"-", xml:"-"`
}

type metadataListDocumentsInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type ListDocumentsOutput struct {
	DocumentIdentifiers []*DocumentIdentifier `locationNameList:"DocumentIdentifier" type:"list"`
	NextToken           *string               `type:"string"`

	metadataListDocumentsOutput `json:"-", xml:"-"`
}

type metadataListDocumentsOutput struct {
	SDKShapeTraits bool `type:"structure"`
}

type UpdateAssociationStatusInput struct {
	AssociationStatus *AssociationStatus `type:"structure" required:"true"`
	InstanceID        *string            `locationName:"InstanceId" type:"string" required:"true"`
	Name              *string            `type:"string" required:"true"`

	metadataUpdateAssociationStatusInput `json:"-", xml:"-"`
}

type metadataUpdateAssociationStatusInput struct {
	SDKShapeTraits bool `type:"structure"`
}

type UpdateAssociationStatusOutput struct {
	AssociationDescription *AssociationDescription `type:"structure"`

	metadataUpdateAssociationStatusOutput `json:"-", xml:"-"`
}

type metadataUpdateAssociationStatusOutput struct {
	SDKShapeTraits bool `type:"structure"`
}