// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package greengrassv2 provides the client and types for making API
// requests to AWS IoT Greengrass V2.
//
// AWS IoT Greengrass brings local compute, messaging, data management, sync,
// and ML inference capabilities to edge devices. This enables devices to collect
// and analyze data closer to the source of information, react autonomously
// to local events, and communicate securely with each other on local networks.
// Local devices can also communicate securely with AWS IoT Core and export
// IoT data to the AWS Cloud. AWS IoT Greengrass developers can use AWS Lambda
// functions and components to create and deploy applications to fleets of edge
// devices for local operation.
//
// AWS IoT Greengrass Version 2 provides a new major version of the AWS IoT
// Greengrass Core software, new APIs, and a new console. Use this API reference
// to learn how to use the AWS IoT Greengrass V2 API operations to manage components,
// manage deployments, and core devices.
//
// For more information, see What is AWS IoT Greengrass? (https://docs.aws.amazon.com/greengrass/v2/developerguide/what-is-iot-greengrass.html)
// in the AWS IoT Greengrass V2 Developer Guide.
//
// See https://docs.aws.amazon.com/goto/WebAPI/greengrassv2-2020-11-30 for more information on this service.
//
// See greengrassv2 package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/greengrassv2/
//
// Using the Client
//
// To contact AWS IoT Greengrass V2 with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the AWS IoT Greengrass V2 client GreengrassV2 for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/greengrassv2/#New
package greengrassv2
