// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package supportapp provides the client and types for making API
// requests to AWS Support App.
//
// You can use the Amazon Web Services Support App in Slack API to manage your
// support cases in Slack for your Amazon Web Services account. After you configure
// your Slack workspace and channel with the Amazon Web Services Support App,
// you can perform the following tasks directly in your Slack channel:
//
//   - Create, search, update, and resolve your support cases
//
//   - Request service quota increases for your account
//
//   - Invite Amazon Web Services Support agents to your channel so that you
//     can chat directly about your support cases
//
// For more information about how to perform these actions in Slack, see the
// following documentation in the Amazon Web Services Support User Guide:
//
//   - Amazon Web Services Support App in Slack (https://docs.aws.amazon.com/awssupport/latest/user/aws-support-app-for-slack.html)
//
//   - Joining a live chat session with Amazon Web Services Support (https://docs.aws.amazon.com/awssupport/latest/user/joining-a-live-chat-session.html)
//
//   - Requesting service quota increases (https://docs.aws.amazon.com/awssupport/latest/user/service-quota-increase.html)
//
//   - Amazon Web Services Support App commands in Slack (https://docs.aws.amazon.com/awssupport/latest/user/support-app-commands.html)
//
// You can also use the Amazon Web Services Management Console instead of the
// Amazon Web Services Support App API to manage your Slack configurations.
// For more information, see Authorize a Slack workspace to enable the Amazon
// Web Services Support App (https://docs.aws.amazon.com/awssupport/latest/user/authorize-slack-workspace.html).
//
//   - You must have a Business or Enterprise Support plan to use the Amazon
//     Web Services Support App API.
//
//   - For more information about the Amazon Web Services Support App endpoints,
//     see the Amazon Web Services Support App in Slack endpoints (https://docs.aws.amazon.com/general/latest/gr/awssupport.html#awssupport_app_region)
//     in the Amazon Web Services General Reference.
//
// See https://docs.aws.amazon.com/goto/WebAPI/support-app-2021-08-20 for more information on this service.
//
// See supportapp package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/supportapp/
//
// # Using the Client
//
// To contact AWS Support App with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the AWS Support App client SupportApp for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/supportapp/#New
package supportapp
