// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package cloudtraildata provides the client and types for making API
// requests to AWS CloudTrail Data Service.
//
// The CloudTrail Data Service lets you ingest events into CloudTrail from any
// source in your hybrid environments, such as in-house or SaaS applications
// hosted on-premises or in the cloud, virtual machines, or containers. You
// can store, access, analyze, troubleshoot and take action on this data without
// maintaining multiple log aggregators and reporting tools. After you run PutAuditEvents
// to ingest your application activity into CloudTrail, you can use CloudTrail
// Lake to search, query, and analyze the data that is logged from your applications.
//
// See https://docs.aws.amazon.com/goto/WebAPI/cloudtrail-data-2021-08-11 for more information on this service.
//
// See cloudtraildata package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtraildata/
//
// # Using the Client
//
// To contact AWS CloudTrail Data Service with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the AWS CloudTrail Data Service client CloudTrailData for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/cloudtraildata/#New
package cloudtraildata
