// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package pipes provides the client and types for making API
// requests to Amazon EventBridge Pipes.
//
// Amazon EventBridge Pipes connects event sources to targets. Pipes reduces
// the need for specialized knowledge and integration code when developing event
// driven architectures. This helps ensures consistency across your company’s
// applications. With Pipes, the target can be any available EventBridge target.
// To set up a pipe, you select the event source, add optional event filtering,
// define optional enrichment, and select the target for the event data.
//
// See https://docs.aws.amazon.com/goto/WebAPI/pipes-2015-10-07 for more information on this service.
//
// See pipes package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/pipes/
//
// # Using the Client
//
// To contact Amazon EventBridge Pipes with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the Amazon EventBridge Pipes client Pipes for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/pipes/#New
package pipes
