// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package frauddetector provides the client and types for making API
// requests to Amazon Fraud Detector.
//
// This is the Amazon Fraud Detector API Reference. This guide is for developers
// who need detailed information about Amazon Fraud Detector API actions, data
// types, and errors. For more information about Amazon Fraud Detector features,
// see the Amazon Fraud Detector User Guide (https://docs.aws.amazon.com/frauddetector/latest/ug/).
//
// We provide the Query API as well as AWS software development kits (SDK) for
// Amazon Fraud Detector in Java and Python programming languages.
//
// The Amazon Fraud Detector Query API provides HTTPS requests that use the
// HTTP verb GET or POST and a Query parameter Action. AWS SDK provides libraries,
// sample code, tutorials, and other resources for software developers who prefer
// to build applications using language-specific APIs instead of submitting
// a request over HTTP or HTTPS. These libraries provide basic functions that
// automatically take care of tasks such as cryptographically signing your requests,
// retrying requests, and handling error responses, so that it is easier for
// you to get started. For more information about the AWS SDKs, see Tools to
// build on AWS (https://docs.aws.amazon.com/https:/aws.amazon.com/tools/).
//
// See https://docs.aws.amazon.com/goto/WebAPI/frauddetector-2019-11-15 for more information on this service.
//
// See frauddetector package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/frauddetector/
//
// # Using the Client
//
// To contact Amazon Fraud Detector with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the Amazon Fraud Detector client FraudDetector for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/frauddetector/#New
package frauddetector
