// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package opensearchserverless provides the client and types for making API
// requests to OpenSearch Service Serverless.
//
// Use the Amazon OpenSearch Serverless API to create, configure, and manage
// OpenSearch Serverless collections and security policies.
//
// OpenSearch Serverless is an on-demand, pre-provisioned serverless configuration
// for Amazon OpenSearch Service. OpenSearch Serverless removes the operational
// complexities of provisioning, configuring, and tuning your OpenSearch clusters.
// It enables you to easily search and analyze petabytes of data without having
// to worry about the underlying infrastructure and data management.
//
// To learn more about OpenSearch Serverless, see What is Amazon OpenSearch
// Serverless? (https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless-overview.html)
//
// See https://docs.aws.amazon.com/goto/WebAPI/opensearchserverless-2021-11-01 for more information on this service.
//
// See opensearchserverless package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/opensearchserverless/
//
// # Using the Client
//
// To contact OpenSearch Service Serverless with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the OpenSearch Service Serverless client OpenSearchServerless for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/opensearchserverless/#New
package opensearchserverless
