// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package emriface provides an interface that satisfies the emr service.
package emriface

import (
	"github.com/awslabs/aws-sdk-go/aws/awserr"
	"github.com/awslabs/aws-sdk-go/service/emr"
)

type EMRAPI interface {
	AddInstanceGroups(*emr.AddInstanceGroupsInput) (*emr.AddInstanceGroupsOutput, awserr.Error)

	AddJobFlowSteps(*emr.AddJobFlowStepsInput) (*emr.AddJobFlowStepsOutput, awserr.Error)

	AddTags(*emr.AddTagsInput) (*emr.AddTagsOutput, awserr.Error)

	DescribeCluster(*emr.DescribeClusterInput) (*emr.DescribeClusterOutput, awserr.Error)

	DescribeJobFlows(*emr.DescribeJobFlowsInput) (*emr.DescribeJobFlowsOutput, awserr.Error)

	DescribeStep(*emr.DescribeStepInput) (*emr.DescribeStepOutput, awserr.Error)

	ListBootstrapActions(*emr.ListBootstrapActionsInput) (*emr.ListBootstrapActionsOutput, awserr.Error)

	ListClusters(*emr.ListClustersInput) (*emr.ListClustersOutput, awserr.Error)

	ListInstanceGroups(*emr.ListInstanceGroupsInput) (*emr.ListInstanceGroupsOutput, awserr.Error)

	ListInstances(*emr.ListInstancesInput) (*emr.ListInstancesOutput, awserr.Error)

	ListSteps(*emr.ListStepsInput) (*emr.ListStepsOutput, awserr.Error)

	ModifyInstanceGroups(*emr.ModifyInstanceGroupsInput) (*emr.ModifyInstanceGroupsOutput, awserr.Error)

	RemoveTags(*emr.RemoveTagsInput) (*emr.RemoveTagsOutput, awserr.Error)

	RunJobFlow(*emr.RunJobFlowInput) (*emr.RunJobFlowOutput, awserr.Error)

	SetTerminationProtection(*emr.SetTerminationProtectionInput) (*emr.SetTerminationProtectionOutput, awserr.Error)

	SetVisibleToAllUsers(*emr.SetVisibleToAllUsersInput) (*emr.SetVisibleToAllUsersOutput, awserr.Error)

	TerminateJobFlows(*emr.TerminateJobFlowsInput) (*emr.TerminateJobFlowsOutput, awserr.Error)
}