// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package elasticinference provides the client and types for making API
// requests to Amazon Elastic  Inference.
//
// Elastic Inference public APIs.
//
// February 15, 2023: Starting April 15, 2023, AWS will not onboard new customers
// to Amazon Elastic Inference (EI), and will help current customers migrate
// their workloads to options that offer better price and performance. After
// April 15, 2023, new customers will not be able to launch instances with Amazon
// EI accelerators in Amazon SageMaker, Amazon ECS, or Amazon EC2. However,
// customers who have used Amazon EI at least once during the past 30-day period
// are considered current customers and will be able to continue using the service.
//
// See https://docs.aws.amazon.com/goto/WebAPI/elastic-inference-2017-07-25 for more information on this service.
//
// See elasticinference package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/elasticinference/
//
// # Using the Client
//
// To contact Amazon Elastic  Inference with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the Amazon Elastic  Inference client ElasticInference for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/elasticinference/#New
package elasticinference
