name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feat-**'

jobs:

  full-test:
    name: Full SDK and tools test
    # Tests for actively maintained Go versions.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version:
          - 1.19.x
          - 1.20.x
          - 1.21.x
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      shell: bash
      # SDK is currently being released with go 1.18, this cannot perform
      # ci-tests task until the release system is updated to go 1.19.
      run: make unit-no-verify
