// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package elasticbeanstalk

const (

	// AWS CodeBuild is not available in the specified region.
	ErrCodeCodeBuildNotInServiceRegionException = "CodeBuildNotInServiceRegionException"

	// The specified account does not have sufficient privileges for one of more
	// AWS services.
	ErrCodeInsufficientPrivilegesException = "InsufficientPrivilegesException"

	// One or more input parameters is not valid. Please correct the input parameters
	// and try the operation again.
	ErrCodeInvalidRequestException = "InvalidRequestException"

	// Cannot modify the managed action in its current state.
	ErrCodeManagedActionInvalidStateException = "ManagedActionInvalidStateException"

	// Unable to perform the specified operation because another operation that
	// effects an element in this activity is already in progress.
	ErrCodeOperationInProgressException = "OperationInProgressFailure"

	// The specified S3 bucket does not belong to the S3 region in which the service
	// is running. The following regions are supported:
	//
	//    * IAD/us-east-1
	//
	//    * PDX/us-west-2
	//
	//    * DUB/eu-west-1
	ErrCodeS3LocationNotInServiceRegionException = "S3LocationNotInServiceRegionException"

	// The specified account does not have a subscription to Amazon S3.
	ErrCodeS3SubscriptionRequiredException = "S3SubscriptionRequiredException"

	// A generic service exception has occurred.
	ErrCodeServiceException = "ServiceException"

	// Unable to delete the Amazon S3 source bundle associated with the application
	// version. The application version was deleted successfully.
	ErrCodeSourceBundleDeletionException = "SourceBundleDeletionFailure"

	// The specified account has reached its limit of application versions.
	ErrCodeTooManyApplicationVersionsException = "TooManyApplicationVersionsException"

	// The specified account has reached its limit of applications.
	ErrCodeTooManyApplicationsException = "TooManyApplicationsException"

	// The specified account has reached its limit of Amazon S3 buckets.
	ErrCodeTooManyBucketsException = "TooManyBucketsException"

	// The specified account has reached its limit of configuration templates.
	ErrCodeTooManyConfigurationTemplatesException = "TooManyConfigurationTemplatesException"

	// The specified account has reached its limit of environments.
	ErrCodeTooManyEnvironmentsException = "TooManyEnvironmentsException"
)
